version: "2"
services:
  frontend:
    build: ./client
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network
  backend:
    build: ./server
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - app-network
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email reotamcoding@gmail.com --agree-tos --no-eff-email --staging -d quizard.reotamai.me
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/reo/view
      o: bind
networks:
  app-network:
    driver: bridge
