version: "1"
services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
  backend:
    build: ./server
    ports:
      - "8000:80"
  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
