import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";

const geistSans = localFont({
  // TODO: Find a way to not use relative path for this?
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // set global app wide settings here like font and others
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1>
          Global <strong>ALL PAGES LAYOUT</strong>
        </h1>
        {children}
      </body>
    </html>
  );
}

/*
PUBLIC ROUTES: 
/                                     <- landing page
/signin                               <- Signin page
/signup                               <- Signup page
/cards                                <- Top trending collections
/id/[userId]                          <- User profile listing all a user's collections
/id/[userId]/[collectionId]           <- Listing all the cards in that collection
/id/[userId]/[collectionId]/[cardId]  <- Details the card

PRIVATE ROUTES: 
// General settings interactions
/settings                                         <- website settings? Maybe light mode or langauge
/id/[userId]/settings                             <- User Specific settings (change email, username, etc)

// Collection interactions
/id/[userId]/new                                  <- Create new collection
/id/[userId]/[collectionId]/settings              <- Collection settings (reset statistics, etc...)
/id/[userId]/[collectionId]/statistics            <- Collection statistics

/id/[userId]/[collectionId]/new                   <- New card in specified collection
/id/[userId]/[collectionId]/[cardId]/settings     <- Card specific settings (reset statistics, etc...)
/id/[userId]/[collectionId]/[cardId]/statistics   <- Card statistics
*/
