name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: "dummy-api-key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r server/requirements.txt

      - name: Run tests
        run: |
          cd server 
          python -m pytest

      - name: Set up SSH
        if: success()
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean Droplet
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd /home/reo/quizard/
            git checkout main
            git pull
            docker-compose down
            docker system prune -a -f
            docker-compose up -d --build
          EOF
